name: PR Preview

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: peter-evans/create-or-update-comment@v2
        id: couc
        with:
          body: âŒ› Deploy Preview - Build in Progress
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.BOT }}

      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - if: ${{ github.event.action == "opened"}}
        run: gh repo create is-a-dev-bot/${{ github.event.pull_request.number }} --public
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run ghbuild

      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BOT }}
          publish_dir: ./build
          external_repository: is-a-dev-bot/${{ github.event.pull_request.number }}

      - name: Sleep to make sure page gets updated
        run: sleep 1m
        shell: bash

      - name: Comment Result
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            âœ”ï¸ Deploy Preview Ready
            ğŸ˜ Preview: https://preview.beta.is-a.dev/${{ github.event.pull_request.number }}
            ğŸ” Deploy Log: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          comment-id: ${{ steps.couc.outputs.comment-id }}
          edit-mode: replace
          token: ${{ secrets.BOT }}

      - if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            âŒ Deploy Preview Failed
            ğŸ” Deploy Log: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          comment-id: ${{ steps.couc.outputs.comment-id }}
          edit-mode: replace
          token: ${{ secrets.BOT }}
